name: Cross-Compile Car Controls to aarch64

on:
  push:
    branches:
      - main
    paths:
      - 'car_controls/**'
  pull_request:
    branches:
      - main
    paths:
      - 'car_controls/**'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy Files to Docker
        run: |
          if [ -d "/home/michel/docker/car_controls" ]; then
            rm -rf /home/michel/docker/car_controls
          fi
          cp -r /home/michel/actions-runner/_work/HotWheels-Cluster/HotWheels-Cluster/car_controls /home/michel/docker/

      - name: Build for AArch64
        run: |
          cd /home/michel/docker
          docker exec sad_curran /bin/bash -c "cd car_controls && make"

      - name: Upload AArch64 Executable
        uses: actions/upload-artifact@v4
        with:
          name: aarch64-car-controls
          path: /home/michel/docker/car_controls/aarch64-car-controls
