name: Car Controls
on:
  push:
    branches:
      - 43-github-actions-compilation
  pull_request:
    branches:
      - 43-github-actions-compilation
jobs:
  build-and-deliver:
    runs-on: ubuntu-latest
    container:
      image: arm64v8/ubuntu:22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y \
            build-essential \
            crossbuild-essential-arm64 \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-ttf-dev \
            libsdl2-mixer-dev \
            gcc \
            g++ \
            make \
            wget \
            ca-certificates
      
      - name: Compile car controls
        run: |
          cd car_controls
          make
      
      - name: Create Artifact
        uses: actions/upload-artifact@v3
        with:
          name: car_controls
          path: car_controls/car_controls