name: Cross-Compile Car Controls to aarch64

on:
  push:
    branches:
      - 43-github-actions-compilation
  pull_request:
    branches:
      - 43-github-actions-compilation

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build for AArch64
        run: |
          echo $PWD

      - name: Upload AArch64 Executable
        uses: actions/upload-artifact@v3
        with:
          name: aarch64-executable
          path: build/car_controls