name: Cross-Compile Car Controls to aarch64

on:
  push:
    branches:
      - 43-github-actions-compilation
  pull_request:
    branches:
      - 43-github-actions-compilation

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Cross-Compiler dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Build for AArch64
        run: |
          cd car_controls
          mkdir -p build && cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=../aarch64-toolchain.cmake \
                -DSDL2_INCLUDE_DIR=/usr/aarch64-linux-gnu/include/SDL2 \
                -DSDL2_LIBRARY=/usr/aarch64-linux-gnu/lib/libSDL2.so ..
          make
        #aarch64-linux-gnu-gcc -o build/car_controls Jetcar.cpp Jetcar.hpp main.cpp

      - name: Upload AArch64 Executable
        uses: actions/upload-artifact@v3
        with:
          name: aarch64-executable
          path: build/car_controls