name: Cross-Compile Car Controls to aarch64

on:
  push:
    branches:
      - testing-control-scripts
  pull_request:
    branches:
      - testing-control-scripts

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy Files to Docker
        run: |
          if [ -d "/home/michel/docker/car_controls" ]; then
            rm -rf /home/michel/docker/car_controls
          fi
          cp -r /home/michel/actions-runner/_work/HotWheels-Cluster/HotWheels-Cluster/car_controls /home/michel/docker/

      - name: Build for AArch64
        run: |
          cd /home/michel/docker
          docker exec sad_curran /bin/bash -c "cd car_controls && make"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          files: /home/michel/docker/car_controls/aarch64-car-controls
          name: Release ${{ steps.tag.outputs.new_tag }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
