name: Cross-Compile Cluster to aarch64

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
  pull_request:
    branches:
      - main
    paths:
      - 'app/**'

jobs:
  run-on-self-hosted:
    runs-on: [self-hosted, seame-computer-1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build arm64 executable
        run: |
          cd app
          mkdir build
          cd build
          ~/qtjetson/qt5.15/bin/qmake ../root.pro
          make -j$(nproc)

      - name: Run tests
        run: |
          cd app/build
          ./HotWheels-tests

      - name: Deploy executable to target
        run: |
          rsync -avz --rsync-path="sudo rsync" --delete app/build/HotWheels-app $JETSON:/home/hotweels/apps/

  generate-doxygen-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen

      - name: Run Doxygen
        run: doxygen Doxyfile

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/
          git commit -m 'Update Doxygen documentation'
          git push
