name: Build Documentation

on:
  workflow_dispatch:

jobs:
  run-on-self-hosted:
    runs-on: [self-hosted, seame-computer-1]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Go to the repository
        run: cd $GITHUB_WORKSPACE

      - name: List the files in the repository
        run: ls -la

      - name: Run Doxygen
        run: doxygen Doxyfile

      - name: Copy documentation
        run: |
          cp -r $GITHUB_WORKSPACE/docs ~/Documents/documentation-branch/docs
          pwd

      - name: Execute script to update documentation and coverage reports
        run: |
          /bin/bash -c "~/Documents/documentation-branch/update.sh"
