name: Cross-Compile Cluster to aarch64

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
  pull_request:
    branches:
      - main
    paths:
      - 'app/**'

jobs:
  run-on-self-hosted:
    runs-on: [self-hosted, seame-computer-1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build arm64 executable
        run: |
          cd app
          mkdir build
          cd build
          ~/qtjetson/qt5.15/bin/qmake ../HotWheels-app.pro
          make -j$(nproc)

      - name: Deploy executable to target
        run: |
          rsync -avz --rsync-path="sudo rsync" --delete app/build/HotWheels-app $JETSON:/home/hotweels/apps2/
