name: Cross-Compile Cluster to aarch64

on:
  push:
    branches:
      - test-coverage
    # paths:
    #   - 'apps/cluster/**'
    #   - 'ZeroMQ/**'
  pull_request:
    branches:
      - test-coverage
    # paths:
    #   - 'apps/cluster/**'
    #   - 'ZeroMQ/**'

env:
  DIR: apps/cluster

jobs:
  compile-and-test:
    runs-on: [self-hosted, seame-computer-1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build executable
        run: |
          cd $DIR
          mkdir build
          cd build
          ~/new_qtjetson/qt5.15/bin/qmake ../HotWheels-app.pro
          make -j$(nproc)
          rm -rf *.o

      - name: Build executable for integration testing
        run: |
          cd $DIR/build
          qmake ../HotWheels-integration-tests.pro
          make -j$(nproc)
          rm -rf *.o

      - name: Build executable for unit testing
        run: |
          cd $DIR/build
          qmake ../HotWheels-unit-tests.pro
          make -j$(nproc)

      - name: Run integration tests
        run: |
          cd $DIR/build
          ./HotWheels-integration-tests

      - name: Run integration tests
        run: |
          cd $DIR/build
          ./HotWheels-unit-tests

      - name: Deploy executable to target
        env:
          SSHPASS: ${{ secrets.JETSON_PASSWORD }}
        run: |
          sshpass -e rsync -avz --rsync-path="sudo rsync" --delete $DIR/build/HotWheels-app jetson@100.108.203.64:/home/jetson/apps/test

  coverage-report:
    needs: compile-and-test
    runs-on: [self-hosted, seame-computer-1]
    steps:
      - name: Generate coverage report
        run: |
          cd $DIR/build
          lcov --capture --directory . --output-file full.info
          lcov --remove full.info '*/moc_*.cpp' '*/moc_*.gcda' '*/moc_*.gcno' '*/test_*' '*/Mock*' '*/usr/*' '*/Qt*' --output-file filtered.info
          genhtml filtered.info --output-directory coverage-cluster
