name: Cross-Compile Car Controls to aarch64

on:
  push:
    branches:
      - test-coverage
    paths:
      - 'apps/car_controls/**'
      - 'ZeroMQ/**'
  pull_request:
    branches:
      - test-coverage
    paths:
      - 'apps/car_controls/**'
      - 'ZeroMQ/**'

env:
  DIR: apps/car_controls

jobs:
  run-on-self-hosted:
    runs-on: [self-hosted, seame-computer-1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build arm64 executable and tests executable
        run: |
          cd $DIR
          mkdir build
          cd build
          ~/qtjetson/qt5.15/bin/qmake ../car-controls-qt.pro
          make -j$(nproc)

      - name: Build arm64 executable for testing
        run: |
          cd $DIR
          cd build
          ~/qtjetson/qt5.15/bin/qmake ../car-controls-tests.pro
          make -j$(nproc)

      - name: Deploy tests on Jetson
        env:
          SSHPASS: ${{ secrets.JETSON_PASSWORD }}
        run: |
          sshpass -e rsync -avz --rsync-path="sudo rsync" --delete $DIR/build/car-controls-tests hotweels@10.21.221.78:/home/hotweels/apps/test

      - name: Run tests
        env:
          SSHPASS: ${{ secrets.JETSON_PASSWORD }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no hotweels@10.21.221.78 \
            '/home/hotweels/apps/tests/car-controls-tests'

      - name: Deploy executable to target
        env:
          SSHPASS: ${{ secrets.JETSON_PASSWORD }}
        run: |
          sshpass -e rsync -avz --rsync-path="sudo rsync" --delete $DIR/build/car-controls-qt hotweels@10.21.221.78:/home/hotweels/apps/test
