name: Build Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
  pull_request:
    branches:
      - main
    paths:
      - 'app/**'

jobs:
  run-on-self-hosted:
    runs-on: [self-hosted, home-1]
    steps:
      - name: Go to the repository
        # run: cd ~/Documents/${{ github.repository }}
        run: cd ~/Documents/${{ github.event.repository.name }}

      - name: Run Doxygen
        run: doxygen Doxyfile
