name: Cross-Compile Car Controls to aarch64

on:
  push:
    branches:
      - fix-yaml-files
    paths:
      - 'car_controls/**'
  pull_request:
    branches:
      - fix-yaml-files
    paths:
      - 'car_controls/**'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy Files to Docker
        run: |
          if [ -d "/home/michel/docker/car_controls" ]; then
            rm -rf /home/michel/docker/car_controls
          fi
          cp -r /home/michel/actions-runner/_work/HotWheels-Cluster/HotWheels-Cluster/car_controls /home/michel/docker/

      - name: Build for AArch64
        run: |
          cd /home/michel/docker
          docker exec sad_curran /bin/bash -c "cd car_controls && make"

      - name: Running tests
        run: |
          cd /home/michel/docker
          docker exec sad_curran /bin/bash -c "cd car_controls && make test"

      - name: Get latest tag and increment
        id: tag
        run: |
          git fetch --tags --force
          git fetch origin # Ensures the branch is up to date
          latest_tag=$(git tag --sort=-v:refname | head -n 1)
          if [ -z "$latest_tag" ]; then
            latest_tag="v1.0.0"
          fi
          major=$(echo $latest_tag | cut -d. -f1 | tr -d 'v')
          minor=$(echo $latest_tag | cut -d. -f2)
          patch=$(echo $latest_tag | cut -d. -f3)
          new_tag="v$major.$minor.$((patch + 1))"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create Release for aarch64
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          files: /home/michel/docker/car_controls/aarch64-car-controls
          name: Release ${{ steps.tag.outputs.new_tag }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Create artifact for aarch64
        uses: actions/upload-artifact@v4
        with:
          name: aarch64-car-controls
          path: /home/michel/docker/car_controls/aarch64-car-controls
