name: Deploy Documentation

on:
  push:
    branches:
      - page

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure write permission to push docs to the repository
      pages: write     # Grant permission to deploy to GitHub Pages
      id-token: write  # Grant permission for workflow actions

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen

      - name: Install Graphviz
        run: sudo apt-get install -y graphviz

      - name: Run Doxygen
        run: doxygen Doxyfile
