name: Cross-Compile Car Controls to aarch64

on:
  push:
    branches:
      - fix-app-shutdown-controls
    ##paths:
      ##- 'car_controls/**'
  pull_request:
    branches:
      - fix-app-shutdown-controls
    ##paths:
      ##- 'car_controls/**'

jobs:
  run-on-self-hosted:
    runs-on: [self-hosted, seame-computer-2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build arm64 executable
        run: |
          cd car_controls
          mkdir build
          cd build
          ~/qtjetson/qt5.15/bin/qmake ../car-controls-qt.pro
          make -j$(nproc)

      - name: Build x86 executable for testing
        run: |
          cd car_controls
          mkdir build-x86
          cd build-x86
          qmake ../root.pro
          make -j$(nproc)

      - name: Run tests
        run: |
          cd car_controls/build-x86
          ./car-controls-tests

      - name: Deploy executable to target
        env:
          SSHPASS: ${{ secrets.JETSON_PASSWORD }}
        run: |
          sshpass -e rsync -avz --rsync-path="sudo rsync" --delete car_controls/build/car-controls-qt hotweels@10.21.221.78:/home/hotweels/apps/
