name: Cross-Compile Cluster to aarch64

on:
  push:
    branches:
      - solve-car-controls-problem
    #paths:
      #- 'car_controls/**'
  pull_request:
    branches:
      - solve-car-controls-problem
    #paths:
      #- 'car_controls/**'

jobs:
  run-on-self-hosted:
    runs-on: [self-hosted, seame-computer-1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build arm64 executable
        run: |
          cd car_controls
          mkdir build
          cd build
          ~/qtjetson/qt5.15/bin/qmake ../car-controls-qt.pro
          make -j$(nproc)

      - name: Debug JETSON variable
        run: |
          echo "JETSON is set to: $JETSON"

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$JETSON_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 10.21.221.78 >> ~/.ssh/known_hosts

      - name: Deploy executable to target
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_rsa" --rsync-path="sudo rsync" \
            --delete car_controls/build/car-controls-qt hotweels@10.21.221.78:/home/hotweels/apps

