name: Cross-Compile Cluster to aarch64

on:
  push:
    branches:
      - solve-car-controls-problem
    #paths:
      #- 'car_controls/**'
  pull_request:
    branches:
      - solve-car-controls-problem
    #paths:
      - 'car_controls/**'

jobs:
  run-on-self-hosted:
    runs-on: [self-hosted, seame-computer-1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build arm64 executable
        run: |
          cd car_controls
          mkdir build
          cd build
          ~/qtjetson/qt5.15/bin/qmake ../controls.pro
          make -j$(nproc)

      - name: Deploy executable to target
        run: |
          rsync -avz --rsync-path="sudo rsync" --delete car_controls/build/car-controls-qt $JETSON:/home/hotweels/apps
