name: Cross-Compile Cluster to aarch64

on:
  push:
    branches:
      - fix-car-controls
    #paths:
      #- 'app/**'
  pull_request:
    branches:
      - fix-car-controls
    #paths:
      #- 'app/**'

jobs:
  run-on-self-hosted:
    runs-on: [self-hosted, seame-computer-2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build arm64 executable
        run: |
          cd app
          mkdir build
          cd build
          ~/qtjetson/qt5.15/bin/qmake ../root.pro
          make -j$(nproc)

      - name: Build x86 executable for testing
        run: |
          cd app
          mkdir build-x86
          cd build-x86
          qmake ../root.pro
          make -j$(nproc)

      - name: Run tests
        run: |
          cd app/build-x86
          ./HotWheels-tests

      #- name: Deploy executable to target
        #env:
          #SSHPASS: ${{ secrets.JETSON_PASSWORD }}
        #run: |
          #sshpass -e rsync -avz --rsync-path="sudo rsync" --delete app/build/HotWheels-app hotweels@10.21.221.78:/home/hotweels/apps/
