name: Cross-Compile Cluster to aarch64

on:
  push:
    branches:
      - model-on-cluster
    paths:
      - 'apps/cluster/**'
  pull_request:
    branches:
      - model-on-cluster
    paths:
      - 'apps/cluster/**'

env:
  DIR: apps/cluster

jobs:
  run-on-self-hosted:
    runs-on: [self-hosted, seame-computer-1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build arm64 executable
        run: |
          cd $DIR
          mkdir build
          cd build
          ~/qtjetson/qt5.15/bin/qmake ../HotWheels-app.pro
          make -j$(nproc)

      - name: Build x86 executable for testing
        run: |
          cd $DIR
          mkdir build-x86
          cd build-x86
          qmake ../root.pro
          make -j$(nproc)
        continue-on-error: true

      - name: Run tests
        run: |
          cd $DIR/build-x86
          ./HotWheels-unit-tests
        continue-on-error: true

      - name: Deploy executable to target
        env:
          SSHPASS: ${{ secrets.JETSON_PASSWORD }}
        run: |
          sshpass -e rsync -avz --rsync-path="sudo rsync" --delete $DIR/build/HotWheels-app hotweels@10.21.221.78:/home/hotweels/apps/test
