name: Cross-Compile Cluster to aarch64

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
  pull_request:
    branches:
      - main
    paths:
      - 'app/**'

jobs:
  run-on-self-hosted:
    runs-on: [self-hosted, seame-computer-2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build arm64 executable
        run: |
          cd app
          mkdir build
          cd build
          ~/qtjetson/qt5.15/bin/qmake ../root.pro
          make -j$(nproc)

      - name: Run tests
        run: |
          cd app/build
          ./HotWheels-tests

      - name: Deploy executable to target
        run: |
          rsync -avz --rsync-path="sudo rsync" --delete app/build/HotWheels-app $JETSON:/home/hotweels/apps/
          sshpass -p 'jetson' scp -r car_controls/build/car-controls-qt hotweels@10.21.221.78:/home/hotweels/apps/
