name: Orchestrator

on:
  workflow_run:
    workflows: [Car Controls, Cluster]
    types:
      - completed
    branches:
      - test-coverage

jobs:
  check-and-trigger-docs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
            sudo apt update
            sudo apt install -y gh

      - name: Check status of both workflows
        id: check
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          REPO="${{ github.repository }}"
          BRANCH="${{ github.event.workflow_run.head_branch }}"
          SHA="${{ github.event.workflow_run.head_sha }}"

          echo "Checking workflow runs for $REPO on branch $BRANCH and commit $SHA"

          # Get successful run of deploy-controls.yml on the same commit
          CONTROLS=$(gh api -H "Accept: application/vnd.github+json" \
            /repos/$REPO/actions/workflows/deploy-controls.yml/runs \
            --jq ".workflow_runs[] | select(.head_sha == \"$SHA\" and .conclusion == \"success\") | .id" | head -n 1)

          # Get successful run of deploy-cluster.yml on the same commit
          CLUSTER=$(gh api -H "Accept: application/vnd.github+json" \
            /repos/$REPO/actions/workflows/deploy-cluster.yml/runs \
            --jq ".workflow_runs[] | select(.head_sha == \"$SHA\" and .conclusion == \"success\") | .id" | head -n 1)

          echo "Car controls workflow run ID on commit $SHA: $CONTROLS"
          echo "Cluster workflow run ID on commit $SHA: $CLUSTER"

          if [[ -z "$CONTROLS" || -z "$CLUSTER" ]]; then
            echo "One or both workflows haven't succeeded on this commit."
            echo "trigger_docs=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "Both workflows succeeded on the same commit."
          echo "trigger_docs=true" >> $GITHUB_OUTPUT

      - name: Trigger documentation workflow
        if: steps.check.outputs.trigger_docs == 'true'
        run: |
          gh workflow run deploy-docs.yml --ref ${{ github.event.workflow_run.head_branch }}
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
