name: Orchestrator

on:
  workflow_run:
    workflows: ["Cross-Compile Car Controls to aarch64", "Cross-Compile Cluster to aarch64"]
    types:
      - completed
    branches:
      - test-coverage

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug workflow run event
        run: |
          echo "Workflow run triggered!"
          echo "Conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Status: ${{ github.event.workflow_run.status }}"
          echo "Branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Workflow: ${{ github.event.workflow_run.workflow.name }}"
