name: Orchestrator

on:
  workflow_run:
    workflows: [Car Controls]
    types:
      - completed
    branches:
      - main

jobs:
  check-and-trigger-docs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
            sudo apt update
            sudo apt install -y gh

      - name: Trigger documentation workflow
        run: |
          gh workflow run deploy-docs.yml --ref ${{ github.event.workflow_run.head_branch }}
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
